/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package h1;

import dbcon.conne;
import static h1.afterlogin.resultSetToTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SPY
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
            initComponents();
            conne.connect();
            deleteStdPanel.setVisible(false);
            deleteTeachPanel.setVisible(false);
            removeAccpnl.setVisible(false);
            addAccPanel.setVisible(false);
            searchStdpnl.setVisible(true);
            searchTeach.setVisible(false);
            viewAcc.setVisible(false);
            Advanced.setVisible(false);
            ResultSet allstdrs;
            try {
            DefaultTableModel j = (DefaultTableModel) adminStdSearchTable.getModel() ;
            PreparedStatement p  = conne.connection.prepareStatement ("Select `id`, `firstName`, `lastName`, `grade` FROM `student`");
            allstdrs = p.executeQuery();
            resultSetToTableModel(allstdrs, adminStdSearchTable);
            allstdrs.close();
            p.close();   
            }
            catch(SQLException e)
            {
            
        }
            
        } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchStd = new javax.swing.JLabel();
        searchTeachlbl = new javax.swing.JLabel();
        viewAllAcc = new javax.swing.JLabel();
        addAccLbl = new javax.swing.JLabel();
        delStdLbl = new javax.swing.JLabel();
        delTeachLbl = new javax.swing.JLabel();
        removeAccLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        advancebtn = new javax.swing.JLabel();
        allInOne = new javax.swing.JPanel();
        deleteStdPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        delteStdIdField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stddelete = new javax.swing.JLabel();
        deleteTeachPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        teachDel = new javax.swing.JLabel();
        teachDelField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        removeAccpnl = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        delUserField = new javax.swing.JTextField();
        remove = new javax.swing.JLabel();
        addAccPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        addAcc = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        searchStdpnl = new javax.swing.JPanel();
        stdSearchChoice = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        stdSearchField = new javax.swing.JTextField();
        StdSearchLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminStdSearchTable = new javax.swing.JTable();
        searchTeach = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        teachSearchField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        searchTeachLBL = new javax.swing.JLabel();
        teachChoice = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchTeachTable = new javax.swing.JTable();
        viewAcc = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        teachSearchField1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        searchTeachLBL1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchTeachTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Advanced = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        deleteallstdlbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        deleteallteachlbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        dleteallacclbl = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        dleteallacclbl1 = new javax.swing.JLabel();
        stdchoice = new javax.swing.JComboBox<>();
        deletestdchoice = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 131, 221));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(8, 87, 147));

        searchStd.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        searchStd.setForeground(new java.awt.Color(133, 197, 31));
        searchStd.setText("Student Search");
        searchStd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchStd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchStdMousePressed(evt);
            }
        });

        searchTeachlbl.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        searchTeachlbl.setForeground(new java.awt.Color(133, 197, 31));
        searchTeachlbl.setText("search Teacher");
        searchTeachlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchTeachlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchTeachlblMousePressed(evt);
            }
        });

        viewAllAcc.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        viewAllAcc.setForeground(new java.awt.Color(133, 197, 31));
        viewAllAcc.setText("View All Account");
        viewAllAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewAllAccMousePressed(evt);
            }
        });

        addAccLbl.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        addAccLbl.setForeground(new java.awt.Color(133, 197, 31));
        addAccLbl.setText("Add Account");
        addAccLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAccLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addAccLblMousePressed(evt);
            }
        });

        delStdLbl.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        delStdLbl.setForeground(new java.awt.Color(133, 197, 31));
        delStdLbl.setText("Delete Student");
        delStdLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delStdLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delStdLblMousePressed(evt);
            }
        });

        delTeachLbl.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        delTeachLbl.setForeground(new java.awt.Color(133, 197, 31));
        delTeachLbl.setText("Delete Teacher");
        delTeachLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delTeachLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delTeachLblMousePressed(evt);
            }
        });

        removeAccLbl.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        removeAccLbl.setForeground(new java.awt.Color(133, 197, 31));
        removeAccLbl.setText("     Remove Account");
        removeAccLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeAccLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeAccLblMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("School Admin");

        logout.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(133, 197, 31));
        logout.setText("LOG OUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        advancebtn.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 11)); // NOI18N
        advancebtn.setForeground(new java.awt.Color(133, 197, 31));
        advancebtn.setText("Advanced");
        advancebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                advancebtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTeachlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewAllAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchStd, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeAccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(delTeachLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addAccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delStdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(advancebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(searchStd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTeachlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewAllAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(delStdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delTeachLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeAccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        allInOne.setBackground(new java.awt.Color(13, 131, 221));

        deleteStdPanel.setBackground(new java.awt.Color(13, 131, 221));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id");

        delteStdIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delteStdIdFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter ID of Student You want To Delete");

        stddelete.setBackground(new java.awt.Color(255, 255, 255));
        stddelete.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 16)); // NOI18N
        stddelete.setForeground(new java.awt.Color(255, 255, 255));
        stddelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/icons8-delete-24.png"))); // NOI18N
        stddelete.setText("Delete");
        stddelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stddeleteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout deleteStdPanelLayout = new javax.swing.GroupLayout(deleteStdPanel);
        deleteStdPanel.setLayout(deleteStdPanelLayout);
        deleteStdPanelLayout.setHorizontalGroup(
            deleteStdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStdPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(deleteStdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(stddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deleteStdPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delteStdIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        deleteStdPanelLayout.setVerticalGroup(
            deleteStdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStdPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel10)
                .addGap(48, 48, 48)
                .addGroup(deleteStdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(delteStdIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        deleteTeachPanel.setBackground(new java.awt.Color(13, 131, 221));

        jLabel11.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID");

        teachDel.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        teachDel.setForeground(new java.awt.Color(255, 255, 255));
        teachDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/icons8-delete-24.png"))); // NOI18N
        teachDel.setText("DELETE");
        teachDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teachDelMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Montserrat Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Teacher Id you want to Delete");

        javax.swing.GroupLayout deleteTeachPanelLayout = new javax.swing.GroupLayout(deleteTeachPanel);
        deleteTeachPanel.setLayout(deleteTeachPanelLayout);
        deleteTeachPanelLayout.setHorizontalGroup(
            deleteTeachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteTeachPanelLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(deleteTeachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(teachDel)
                    .addGroup(deleteTeachPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teachDelField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        deleteTeachPanelLayout.setVerticalGroup(
            deleteTeachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteTeachPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(deleteTeachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(teachDelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(teachDel)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        removeAccpnl.setBackground(new java.awt.Color(13, 131, 221));

        jLabel13.setFont(new java.awt.Font("Montserrat Alternates Light", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Enter the user name the account that you want to remove");

        jLabel14.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USER NAME");

        remove.setBackground(new java.awt.Color(102, 204, 0));
        remove.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 14)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/icons8-remove-24.png"))); // NOI18N
        remove.setText("Remove");
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout removeAccpnlLayout = new javax.swing.GroupLayout(removeAccpnl);
        removeAccpnl.setLayout(removeAccpnlLayout);
        removeAccpnlLayout.setHorizontalGroup(
            removeAccpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeAccpnlLayout.createSequentialGroup()
                .addGroup(removeAccpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeAccpnlLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addComponent(delUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeAccpnlLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeAccpnlLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        removeAccpnlLayout.setVerticalGroup(
            removeAccpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeAccpnlLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(removeAccpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        addAccPanel.setBackground(new java.awt.Color(13, 131, 221));

        jLabel15.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("USER NAME");

        jLabel16.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PASSWORD");

        addAcc.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        addAcc.setForeground(new java.awt.Color(255, 255, 255));
        addAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/icons8-add-user-male-80.png"))); // NOI18N
        addAcc.setText("ADD ACCOUNT ");
        addAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addAccMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Enter The User USER NAME AND PASSWOR");

        javax.swing.GroupLayout addAccPanelLayout = new javax.swing.GroupLayout(addAccPanel);
        addAccPanel.setLayout(addAccPanelLayout);
        addAccPanelLayout.setHorizontalGroup(
            addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAccPanelLayout.createSequentialGroup()
                .addGroup(addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAccPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addAccPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addAcc)
                            .addGroup(addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(addAccPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addAccPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(41, 41, 41)
                                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        addAccPanelLayout.setVerticalGroup(
            addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAccPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(addAcc)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        searchStdpnl.setBackground(new java.awt.Color(13, 131, 221));

        stdSearchChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FirstName", "LastName", "Grade" }));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Search BY");

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Search Student");

        StdSearchLbl.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        StdSearchLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/icons8-google-web-search-50.png"))); // NOI18N
        StdSearchLbl.setText("Search");
        StdSearchLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StdSearchLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StdSearchLblMousePressed(evt);
            }
        });

        adminStdSearchTable.setBackground(new java.awt.Color(13, 131, 221));
        adminStdSearchTable.setForeground(new java.awt.Color(255, 255, 255));
        adminStdSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Fname", "Lname", "grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminStdSearchTable.setRowHeight(40);
        jScrollPane1.setViewportView(adminStdSearchTable);

        javax.swing.GroupLayout searchStdpnlLayout = new javax.swing.GroupLayout(searchStdpnl);
        searchStdpnl.setLayout(searchStdpnlLayout);
        searchStdpnlLayout.setHorizontalGroup(
            searchStdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStdpnlLayout.createSequentialGroup()
                .addGroup(searchStdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchStdpnlLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stdSearchChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(stdSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(StdSearchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchStdpnlLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchStdpnlLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        searchStdpnlLayout.setVerticalGroup(
            searchStdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStdpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(searchStdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdSearchChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(StdSearchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        searchTeach.setBackground(new java.awt.Color(13, 131, 221));

        jPanel13.setBackground(new java.awt.Color(13, 131, 221));

        teachSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachSearchFieldActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Search BY");

        searchTeachLBL.setFont(new java.awt.Font("Montserrat Light", 0, 24)); // NOI18N
        searchTeachLBL.setForeground(new java.awt.Color(255, 255, 255));
        searchTeachLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/search.png"))); // NOI18N
        searchTeachLBL.setText("Search Teacher");
        searchTeachLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchTeachLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchTeachLBLMousePressed(evt);
            }
        });

        teachChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "name", "department", "age" }));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teachChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(teachSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(searchTeachLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teachSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(teachChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addComponent(searchTeachLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        searchTeachTable.setBackground(new java.awt.Color(13, 131, 221));
        searchTeachTable.setForeground(new java.awt.Color(255, 255, 255));
        searchTeachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Department", "age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchTeachTable.setGridColor(new java.awt.Color(13, 131, 221));
        searchTeachTable.setRowHeight(35);
        jScrollPane3.setViewportView(searchTeachTable);

        javax.swing.GroupLayout searchTeachLayout = new javax.swing.GroupLayout(searchTeach);
        searchTeach.setLayout(searchTeachLayout);
        searchTeachLayout.setHorizontalGroup(
            searchTeachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTeachLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(searchTeachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchTeachLayout.setVerticalGroup(
            searchTeachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTeachLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        viewAcc.setBackground(new java.awt.Color(13, 131, 221));

        jPanel14.setBackground(new java.awt.Color(13, 131, 221));

        teachSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachSearchField1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Search ");

        searchTeachLBL1.setFont(new java.awt.Font("Montserrat Light", 0, 24)); // NOI18N
        searchTeachLBL1.setForeground(new java.awt.Color(255, 255, 255));
        searchTeachLBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/search.png"))); // NOI18N
        searchTeachLBL1.setText("Search Account");
        searchTeachLBL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchTeachLBL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchTeachLBL1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teachSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(searchTeachLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teachSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addComponent(searchTeachLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        searchTeachTable1.setBackground(new java.awt.Color(13, 131, 221));
        searchTeachTable1.setForeground(new java.awt.Color(255, 255, 255));
        searchTeachTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Department", "age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchTeachTable1.setGridColor(new java.awt.Color(13, 131, 221));
        searchTeachTable1.setRowHeight(35);
        jScrollPane4.setViewportView(searchTeachTable1);

        javax.swing.GroupLayout viewAccLayout = new javax.swing.GroupLayout(viewAcc);
        viewAcc.setLayout(viewAccLayout);
        viewAccLayout.setHorizontalGroup(
            viewAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAccLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(viewAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewAccLayout.setVerticalGroup(
            viewAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAccLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1/close_ico.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        Advanced.setBackground(new java.awt.Color(13, 131, 221));
        Advanced.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(133, 197, 31));

        deleteallstdlbl.setText("Delete All Student");
        deleteallstdlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteallstdlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteallstdlblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(deleteallstdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteallstdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(133, 197, 31));

        deleteallteachlbl.setText("Delete All Teacher");
        deleteallteachlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteallteachlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteallteachlblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(deleteallteachlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteallteachlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(133, 197, 31));

        dleteallacclbl.setText("Delete All Account");
        dleteallacclbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dleteallacclbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dleteallacclblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dleteallacclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dleteallacclbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(133, 197, 31));

        dleteallacclbl1.setText("Delete All student");
        dleteallacclbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dleteallacclbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dleteallacclbl1MousePressed(evt);
            }
        });

        stdchoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "age", "city", "phone" }));

        deletestdchoice.setText("Delete");
        deletestdchoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deletestdchoiceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(dleteallacclbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stdchoice, 0, 99, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deletestdchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dleteallacclbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdchoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletestdchoice)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdvancedLayout = new javax.swing.GroupLayout(Advanced);
        Advanced.setLayout(AdvancedLayout);
        AdvancedLayout.setHorizontalGroup(
            AdvancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(AdvancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(665, Short.MAX_VALUE))
        );
        AdvancedLayout.setVerticalGroup(
            AdvancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout allInOneLayout = new javax.swing.GroupLayout(allInOne);
        allInOne.setLayout(allInOneLayout);
        allInOneLayout.setHorizontalGroup(
            allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allInOneLayout.createSequentialGroup()
                .addContainerGap(1133, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 136, Short.MAX_VALUE)
                    .addComponent(deleteStdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 136, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allInOneLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteTeachPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 136, Short.MAX_VALUE)
                    .addComponent(removeAccpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 136, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 144, Short.MAX_VALUE)
                    .addComponent(addAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 145, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchStdpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchTeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Advanced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );
        allInOneLayout.setVerticalGroup(
            allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allInOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(874, Short.MAX_VALUE))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(deleteStdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allInOneLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(deleteTeachPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(removeAccpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchStdpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchTeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(allInOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(allInOneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Advanced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
        );

        jLabel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allInOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(allInOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stddeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stddeleteMousePressed
        String id = delteStdIdField.getText();
        try 
        {
            conne.deleteStd( id );
            JOptionPane.showMessageDialog( null ,"Succesfuly Deleted!");
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"Registration Failed Please Try later");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_stddeleteMousePressed

    private void delteStdIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delteStdIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delteStdIdFieldActionPerformed

    private void teachDelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachDelMousePressed
        String id = teachDelField.getText();
        try 
        {
            conne.deleteTeach(id);
            JOptionPane.showMessageDialog( null,"Succesfuly Deleted!");
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog( null,"Registration Failed Please Try later");
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( null,"Unknown Error please Try again");
        }
    }//GEN-LAST:event_teachDelMousePressed

    private void delStdLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delStdLblMousePressed
        
        deleteStdPanel.setVisible(true);
        deleteTeachPanel.setVisible(false);
        addAccPanel.setVisible(false);
        removeAccpnl.setVisible(false);
        searchStdpnl.setVisible(false);
        searchTeach.setVisible(false);
        viewAcc.setVisible(false);
        Advanced.setVisible(false);
    }//GEN-LAST:event_delStdLblMousePressed

    private void delTeachLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delTeachLblMousePressed
        // TODO add your handling code here:
        deleteStdPanel.setVisible(false);
        deleteTeachPanel.setVisible(true);
        removeAccpnl.setVisible(false);
        addAccPanel.setVisible(false);
        searchStdpnl.setVisible(false);
        searchTeach.setVisible(false);
        viewAcc.setVisible(false);
        Advanced.setVisible(false);
    }//GEN-LAST:event_delTeachLblMousePressed

    private void removeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMousePressed
        String user = delUserField.getText();
        try 
        {
            conne.removeAcc(user);
            JOptionPane.showMessageDialog( null,"Succesfuly Deleted!");
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog( null,"Registration Failed Please Try later");
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( null,"Unkown Error , please Try again later.");
        }
    }//GEN-LAST:event_removeMousePressed

    private void removeAccLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAccLblMousePressed
        deleteStdPanel.setVisible(false);
        deleteTeachPanel.setVisible(false);
        removeAccpnl.setVisible(true);
        searchStdpnl.setVisible(false);
        addAccPanel.setVisible(false);
        searchTeach.setVisible(false);
        viewAcc.setVisible(false);
        Advanced.setVisible(false);
    }//GEN-LAST:event_removeAccLblMousePressed

    private void addAccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAccMousePressed
        
        String user = userNameField.getText(), password = passwordField.getText();
        try {
            conne.addAcc(user, password);
             JOptionPane.showMessageDialog( null,"Account Succesfuly Created!");
        } catch(SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog( null,"Registration Failed Please Try later");
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( null,"Unkown Error , please Try again later.");
        }
    }//GEN-LAST:event_addAccMousePressed

    private void addAccLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAccLblMousePressed
        // TODO add your handling code here:
        addAccPanel.setVisible(true);
        deleteStdPanel.setVisible(false);
        deleteTeachPanel.setVisible(false);
        removeAccpnl.setVisible(false);
        searchStdpnl.setVisible(false);
        searchTeach.setVisible(false);
        viewAcc.setVisible(false);
        Advanced.setVisible(false);
    }//GEN-LAST:event_addAccLblMousePressed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        try {
            this.setVisible(false);
            new NewJFrame().setVisible(true);
        } catch (SQLException ex) {
            //Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_logoutMousePressed

    private void StdSearchLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StdSearchLblMousePressed
        
//        deleteStdPanel.setVisible(false);
//        deleteTeachPanel.setVisible(false);
//        removeAccpnl.setVisible(false);
//        addAccPanel.setVisible(false);
//        searchStdpnl.setVisible(true);
        String choice = (String) stdSearchChoice.getSelectedItem();
        String search = stdSearchField.getText();
        ResultSet rs ;
        DefaultTableModel jf = (DefaultTableModel) adminStdSearchTable.getModel() ;
        while(jf.getRowCount() > 0)
        {
            jf.removeRow ( 0 );
        }

        try
        {
            rs = conne.searchStd(choice,search);

            while(rs.next())
            {
                String id = rs.getString("id");
                String fName =rs.getString("firstName");
                String lName = rs.getString("lastName");
                int grade = rs.getInt("grade");
                jf.addRow(new Object[] {id,fName,lName,grade});
            }

        }
        catch(SQLException ex)
        {

        }

    }//GEN-LAST:event_StdSearchLblMousePressed

    private void searchStdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStdMousePressed
            deleteStdPanel.setVisible(false);
            deleteTeachPanel.setVisible(false);
            removeAccpnl.setVisible(false);
            addAccPanel.setVisible(false);
            searchStdpnl.setVisible(true);  
            searchTeach.setVisible(false);
            viewAcc.setVisible(false);
            Advanced.setVisible(false);
        
        ResultSet allstdrs;
        try {
            DefaultTableModel j = (DefaultTableModel) adminStdSearchTable.getModel() ;
            PreparedStatement p  = conne.connection.prepareStatement ("Select `id`, `firstName`, `lastName`, `grade` FROM `student`");
            allstdrs = p.executeQuery();
            resultSetToTableModel(allstdrs, adminStdSearchTable);
            allstdrs.close();
            p.close();   
        }
        catch(SQLException e)
        {
            
        }
        finally
        {
        }
    }//GEN-LAST:event_searchStdMousePressed

    private void searchTeachlblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTeachlblMousePressed
        addAccPanel.setVisible(false);
        deleteStdPanel.setVisible(false);
        deleteTeachPanel.setVisible(false);
        removeAccpnl.setVisible(false);
        searchStdpnl.setVisible(false);
        searchTeach.setVisible(true); 
        viewAcc.setVisible(false);
        Advanced.setVisible(false);
        
        try {
            DefaultTableModel j = (DefaultTableModel) searchTeachTable.getModel() ;
            
            PreparedStatement p  ;
                    p = conne.connection.prepareStatement ("Select `Tid`, `Tname`, `depName`, `age` FROM `teacher` ");
            ResultSet allstdrs;
                    allstdrs = p.executeQuery();
                    System.out.println("kok");
           resultSetToTableModel(allstdrs, searchTeachTable);
//            while(allstdrs.next())
//                {
//                    String id = allstdrs.getString("Tid");
//                    String fName =allstdrs.getString("firstName");
//                    String lName = allstdrs.getString("lastName");
//                    int grade = allstdrs.getInt("grade");
//                    System.out.println(id + " " + fName + " " + lName + " " + grade);
//                    j.addRow(new Object[] {id,fName,lName,grade});
//                }
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchTeachlblMousePressed

    private void teachSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachSearchFieldActionPerformed

    private void searchTeachLBLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTeachLBLMousePressed
        String choice;
        choice = (String) teachChoice.getSelectedItem();
        String search = teachSearchField.getText();
        ResultSet rs ;
        DefaultTableModel jf = (DefaultTableModel) searchTeachTable.getModel() ;
        while(jf.getRowCount() > 0)
        {
            jf.removeRow ( 0 );
        }

        try
        {
            rs = conne.searchTeach(choice,search);

            //System.out.println("whike");
            while( rs.next() )
            {
                String id = rs.getString("Tid");
                String fName =rs.getString("Tname");
                String lName = rs.getString("depName");
                int grade = rs.getInt("age");
                jf.addRow(new Object[] {id,fName,lName,grade});
            }

        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_searchTeachLBLMousePressed

    private void teachSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachSearchField1ActionPerformed

    private void searchTeachLBL1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTeachLBL1MousePressed
        
        String search = teachSearchField1.getText();
        ResultSet rs ;
        DefaultTableModel jf = (DefaultTableModel) searchTeachTable1.getModel() ;
        while(jf.getRowCount() > 0)
        {
            jf.removeRow ( 0 );
        }

        try
        {
            rs = conne.searchAcc(search);

            //System.out.println("whike");
            while( rs.next() )
            {
                String user = rs.getString("user_name");
                String pass =rs.getString("password");
                jf.addRow(new Object[] {user,pass});
            }

        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_searchTeachLBL1MousePressed

    private void viewAllAccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllAccMousePressed
        
        addAccPanel.setVisible(false);
        deleteStdPanel.setVisible(false);
        deleteTeachPanel.setVisible(false);
        removeAccpnl.setVisible(false);
        searchStdpnl.setVisible(false);
        searchTeach.setVisible(false);
        viewAcc.setVisible(true);
        Advanced.setVisible(false);
        
        try {
            DefaultTableModel j = (DefaultTableModel) searchTeachTable1.getModel() ;
            
            PreparedStatement p  ;
                    p = conne.connection.prepareStatement ("SELECT `user_name`, `password` FROM `account` WHERE 1 ");
            ResultSet allstdrs;
                    allstdrs = p.executeQuery();
           resultSetToTableModel(allstdrs, searchTeachTable1);
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewAllAccMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_jPanel1MouseDragged
int x,y;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        try {
            conne.disconnect();
        } catch (SQLException ex) {
            //Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0) ;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void deleteallstdlblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteallstdlblMousePressed
        // TODO add your handling code here:
        try
        {
            conne.deleteAllStd();
            JOptionPane.showMessageDialog(null,"Succefully Deleted All Student");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"UnSuccefully Action , please try again");
        }
    }//GEN-LAST:event_deleteallstdlblMousePressed

    private void deleteallteachlblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteallteachlblMousePressed
        try
        {
            conne.deleteAllTeach();
            JOptionPane.showMessageDialog(null,"Succefully Deleted All Teacher");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"UnSuccefully Action , please try again");
        }
    }//GEN-LAST:event_deleteallteachlblMousePressed

    private void dleteallacclblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dleteallacclblMousePressed
       try
        {
            conne.removeAllAcc();
            JOptionPane.showMessageDialog(null,"Succefully Deleted All Account");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"UnSuccefully Action , please try again");
        }
    }//GEN-LAST:event_dleteallacclblMousePressed

    private void advancebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancebtnMousePressed
        addAccPanel.setVisible(false);
        deleteStdPanel.setVisible(false);
        deleteTeachPanel.setVisible(false);
        removeAccpnl.setVisible(false);
        searchStdpnl.setVisible(false);
        searchTeach.setVisible(false);
        viewAcc.setVisible(false);
        Advanced.setVisible(true);
    }//GEN-LAST:event_advancebtnMousePressed

    private void dleteallacclbl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dleteallacclbl1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dleteallacclbl1MousePressed

    private void deletestdchoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletestdchoiceMousePressed
        String choice = (String) stdchoice.getSelectedItem();
        try
        {
            conne.deleteAllStdChoice(choice);
             JOptionPane.showMessageDialog(null,"Succefully Deleted All Student" + choice );
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null,"UnSuccefully Action , please try again");
        }
        
    }//GEN-LAST:event_deletestdchoiceMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Advanced;
    private javax.swing.JLabel StdSearchLbl;
    private javax.swing.JLabel addAcc;
    private javax.swing.JLabel addAccLbl;
    private javax.swing.JPanel addAccPanel;
    private javax.swing.JTable adminStdSearchTable;
    private javax.swing.JLabel advancebtn;
    private javax.swing.JPanel allInOne;
    private javax.swing.JLabel delStdLbl;
    private javax.swing.JLabel delTeachLbl;
    private javax.swing.JTextField delUserField;
    private javax.swing.JPanel deleteStdPanel;
    private javax.swing.JPanel deleteTeachPanel;
    private javax.swing.JLabel deleteallstdlbl;
    private javax.swing.JLabel deleteallteachlbl;
    private javax.swing.JLabel deletestdchoice;
    private javax.swing.JTextField delteStdIdField;
    private javax.swing.JLabel dleteallacclbl;
    private javax.swing.JLabel dleteallacclbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel remove;
    private javax.swing.JLabel removeAccLbl;
    private javax.swing.JPanel removeAccpnl;
    private javax.swing.JLabel searchStd;
    private javax.swing.JPanel searchStdpnl;
    private javax.swing.JPanel searchTeach;
    private javax.swing.JLabel searchTeachLBL;
    private javax.swing.JLabel searchTeachLBL1;
    private javax.swing.JTable searchTeachTable;
    private javax.swing.JTable searchTeachTable1;
    private javax.swing.JLabel searchTeachlbl;
    private javax.swing.JComboBox<String> stdSearchChoice;
    private javax.swing.JTextField stdSearchField;
    private javax.swing.JComboBox<String> stdchoice;
    private javax.swing.JLabel stddelete;
    private javax.swing.JComboBox<String> teachChoice;
    private javax.swing.JLabel teachDel;
    private javax.swing.JTextField teachDelField;
    private javax.swing.JTextField teachSearchField;
    private javax.swing.JTextField teachSearchField1;
    private javax.swing.JTextField userNameField;
    private javax.swing.JPanel viewAcc;
    private javax.swing.JLabel viewAllAcc;
    // End of variables declaration//GEN-END:variables
}
